### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Mingchen2333** [lordblah/Small-Business-App-Project-1#5]
hi, Jonathan. I have answered the question2.6 to 3.4. when we submit it. should we remove all the example answer?

**Comment by lordblah** [comment]
Hello Ming
Good job, yes we should, I'll remove them right now.

**Comment by Mingchen2333** [comment]
![1](https://user-images.githubusercontent.com/38873150/39965282-e63896a6-564a-11e8-9958-30672b0cf5e7.PNG)
![2](https://user-images.githubusercontent.com/38873150/39965283-ed17abb0-564a-11e8-8618-989c5500b32a.PNG)

**Comment by lordblah** [comment]
Wow, it's looking good. Going to grab what you have programmed and make a stub and driver version, if I find any issues ill post it.
