### ISSUE TITLE
user choice

### ISSUE THREAD

**Issue by lordblah** [lordblah/Small-Business-App-Project-1#6]
bug when the user is inserting choice.

**Comment by lordblah** [comment]
`while (UserInput < 0 || UserInput > 5)
		{
			cout << "Sorry choice, please enter option 1~5: ";
			cin >> UserInput;
		}`
here is the logical error, fixing it right now

**Comment by lordblah** [comment]
added 
`cin.clear();
cin.ignore(INT_MAX, '\n');`

added to code sections where needed

**Comment by Mingchen2333** [comment]
Hello, JONATHAN. I went to LA today. I will put the pointer in our code first. and figure out the problem you have. what it is

**Comment by lordblah** [comment]
its ok, already fixed it.
