### ISSUE TITLE
Odin program

### ISSUE THREAD

**Issue by Mingchen2333** [lordblah/Small-Business-App-Project-1#8]
Hi man, I have sent you the code that work with smart point at CANVAS, check that I think we done!

**Comment by lordblah** [comment]
There is an issue with the quality and price. 
![capture](https://user-images.githubusercontent.com/7691501/40263186-a785c5fa-5ac3-11e8-9f98-15e7e475bbec.PNG)

**Comment by Mingchen2333** [comment]
Lol,is that out of range. Never think about it. Normally people don’t order that much. May be we should make it order more than 100 should contact the manager

**Comment by lordblah** [comment]
Its undefined behavior happening, I didn't input that mush, I used less than 10. Its weird, when I try running my debugger, the whole createRecipt is broken, but when I run it regularly, this happens, and only happens with the first two items. I think it has to do with the way unique pointers work.

**Comment by lordblah** [comment]
think i just fixed the issue, ill get back to you

**Comment by lordblah** [comment]
fixed it, also found a calculation error but fixed that as well

**Comment by lordblah** [comment]
ok going to post the new code
